application: minstrels-and-mayhem
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /fonts
  static_dir: public/fonts

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
