GOTAA.ColumnDataMap = {
  allianceshort : [
    {
      name : "name",
      label : "Name",
      type : "textInput",
      sortable : true,
      searchable : true,
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
      maxlength : "100",
    },
    {
      name : "motto",
      label : "Motto",
      type : "textInput",
      sortable : true,
      searchable : true,
      validations : [
      ],
      maxlength : "200",
    },
  ],
  addmodule : [
    {
      name : "title",
      label : "Title",
      type : "textInput",
      sortable : true,
      searchable : true,
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
      maxlength : "100",
    },
    {
      name : "type",
      label : "Type",
      type : "staticSelect",
      options : [
        {val : 'module', label : 'Simple List of Data', helpblock : 'Used for a list of simple data with title and description (short)'},
        {val : 'challenge', label : 'Challenge', helpblock : 'Used for list of challenges (Ended challenges appear in the expanded view)'},
        {val : 'member-list', label : 'List Of Members', helpblock : 'Used to show a list of members. Has the option to enable members to add/remove themselves.'},
        {val : 'feed', label : 'Feed', helpblock : 'Used to show a list of messages. Description can be pretty long. Description is hidden, user has to click on title to view it.'},
        {val : 'camp', label : 'Camp Items', helpblock : 'Show a list of camp item hoarding list'},
      ],
      sortable : true,
      filterable : true,
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
    },
    {
      name : "desc",
      label : "Description",
      type : "textareaInput",
      sortable : true,
      searchable : true,
    },
    {
      name : "col",
      label : "Column",
      type : "staticSelect",
      options : [
        {val : 0, label : 'Left Column'},
        {val : 1, label : 'Center Column'},
        {val : 2, label : 'Right Column'},
      ],
      sortable : true,
      filterable : true,
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
    },
  ],
  module : [
    {
      name : "title",
      label : "Title",
      type : "textInput",
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
      sortable : true,
      searchable : true,
    },
    {
      name : "desc",
      label : "Description",
      type : "textInput",
      sortable : true,
      searchable : true,
    },
  ],
  challenge : [
    {
      name : "title",
      label : "Title",
      type : "textInput",
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
      sortable : true,
      searchable : true,
    },
    {
      name : "startsAtString",
      label : "Starts At",
      type : "textInput",
      validations : [
        {type : 2, invalidMessage : "Invalid Date"},
      ],
      sortable : true,
      searchable : true,
    },
    {
      name : "challengeStatus",
      label : "Started",
      type : "staticSelect",
      options : [
        {val : 1, label : 'Yet to start'},
        {val : 2, label : 'Started - Waiting to fill'},
        {val : 3, label : 'Started - Swing Away!'},
        {val : 4, label : 'Ended', enableFields : [
          {name : "first", disable : false, enable : true},
          {name : "second", disable : false, enable : true},
          {name : "third", disable : false, enable : true},
        ]},
      ],
      sortable : true,
      filterable : true,
      fromFile : true,
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
    },
    {
      name : "first",
      label : "First",
      type : "dynamicSelect",
      prompt : "None",
      dataValCol : "email",
      dataLabelCol : "name",
      validations : [
        //{type : 0, invalidMessage : "Cant be empty"},
      ],
    },
    {
      name : "second",
      label : "Second",
      type : "dynamicSelect",
      prompt : "None",
      dataValCol : "email",
      dataLabelCol : "name",
      validations : [
        //{type : 0, invalidMessage : "Cant be empty"},
      ],
    },
    {
      name : "third",
      label : "Third",
      type : "dynamicSelect",
      prompt : "None",
      dataValCol : "email",
      dataLabelCol : "name",
      validations : [
        //{type : 0, invalidMessage : "Cant be empty"},
      ],
    },
  ],
  feed : [
    {
      name : "title",
      label : "Title",
      type : "textInput",
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
      sortable : true,
      searchable : true,
    },
    {
      name : "desc",
      label : "Description",
      type : "textareaInput",
      sortable : true,
      searchable : true,
    },
    /*{
      name : "image",
      label : "Image",
      type : "imageUpload",
      btnLabel : "Browse",
      method : "ReadAsDataURI",
      accept : "image/*",
    },*/
  ],
  "member-list" : [
    {
      name : "email",
      label : "Member",
      type : "dynamicSelect",
      prompt : "None",
      dataValCol : "email",
      dataLabelCol : "name",
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
    },
    {
      name : "desc",
      label : "Description",
      type : "textInput",
      validations : [
      ],
      sortable : true,
      searchable : true,
    },
  ],
  invite : [
    {
      name : "email",
      label : "Email",
      type : "textInput",
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
      sortable : true,
      searchable : true,
    },
    {
      name : "permission",
      label : "Position",
      type : "staticSelect",
      options : [
        {val : 2, label : 'Leader'},
        {val : 1, label : 'Officer'},
        {val : 0, label : 'Member'},
      ],
      sortable : true,
      filterable : true,
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
    },
  ],
  permission : [
    {
      name : "oprn",
      label : "Operation",
      type : "staticSelect",
      options : [
        {val : "Alliance", label : "Alliance"},
        {val : "Member", label : "Member"},
        {val : "Module", label : "Module"},
        {val : "ModuleData", label : "ModuleData"},
      ],
      sortable : true,
      filterable : true,
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
    },
    {
      name : "permission",
      label : "Position",
      type : "staticSelect",
      options : [
        {val : 2, label : 'Leader'},
        {val : 1, label : 'Officer'},
        {val : 0, label : 'Member'},
      ],
      sortable : true,
      filterable : true,
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
    },
  ],
  camp : [
    {
      name : "type",
      label : "Type",
      type : "staticSelect",
      options : [
        {val : "Battle", label : "Battle"},
        {val : "Trade", label : "Trade"},
        {val : "Intrigue", label : "Intrigue"},
      ],
      sortable : true,
      filterable : true,
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
    },
    {
      name : "fromlevel",
      label : "From Level",
      type : "staticSelect",
      options : [
        {val : 1, label : "1"},
        {val : 2, label : "2"},
        {val : 3, label : "3"},
        {val : 4, label : "4"},
        {val : 5, label : "5"},
        {val : 6, label : "6"},
        {val : 7, label : "7"},
        {val : 8, label : "8"},
        {val : 9, label : "9"},
        {val : 10, label : "10"},
        {val : 11, label : "11"},
        {val : 12, label : "12"},
        {val : 13, label : "13"},
        {val : 14, label : "14"},
        {val : 15, label : "15"},
        {val : 16, label : "16"},
        {val : 17, label : "17"},
        {val : 18, label : "18"},
        {val : 19, label : "19"},
        {val : 20, label : "20"},
      ],
      sortable : true,
      filterable : true,
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
    },
    {
      name : "tolevel",
      label : "To Level",
      type : "staticSelect",
      options : [
        {val : 1, label : "1"},
        {val : 2, label : "2"},
        {val : 3, label : "3"},
        {val : 4, label : "4"},
        {val : 5, label : "5"},
        {val : 6, label : "6"},
        {val : 7, label : "7"},
        {val : 8, label : "8"},
        {val : 9, label : "9"},
        {val : 10, label : "10"},
        {val : 11, label : "11"},
        {val : 12, label : "12"},
        {val : 13, label : "13"},
        {val : 14, label : "14"},
        {val : 15, label : "15"},
        {val : 16, label : "16"},
        {val : 17, label : "17"},
        {val : 18, label : "18"},
        {val : 19, label : "19"},
        {val : 20, label : "20"},
      ],
      sortable : true,
      filterable : true,
      validations : [
        {type : 0, invalidMessage : "Cant be empty"},
      ],
    },
  ],
};
